# Language
languages:
  supportedLanguages:
    - &default
      locale: en_GB
      code: en
    -
      locale: fr_FR
      code: fr
    -
      locale: br_FR
      code: br
      fallback:
        - fr_FR
  defaultLanguage: *default

layout:
  sizes:
    panelWidth : 400
    topBarHeight: 100
    sideBarWidth: 96
  mobile:
    breakPoint: 640

# Pois
pois:
- apiName: opening_hours
  panelName: hour
  options:
    title: _('Opening hours')
    messages:
      open:
        msg: _('Open')
        color: '#60ad51'
      # soon:
      #   msg: _('Closing soon')
      #   time: 60
      #   color: '#c45713'
      closed:
        msg: _('Closed')
        color: '#8c0212'
- apiName: happy_hours
  panelName: hour
  options:
    title: _('Happy hours')
    messages:
      open:
        msg: _('happy hours!')
        color: '#fcc035'
      soon:
        msg: _('Last pint')
        time: 60
        color: '#3f76e2'
      closed:
        msg: _('Closed')
        color: '#8c0212'
- apiName: brewery
  panelName: brewery
- apiName: phone
  panelName: phone
- apiName: website
  panelName: website
- apiName: wikipedia
  panelName: wiki
- apiName: services_and_information
  panelName: services_information
- apiName: information
  panelName: informations
- apiName: accessibility
  panelName: accessibility
  options:
    -
      key: wheelchair
      labels:
        true: _('Wheelchair accessible')
        limited: _('Limited wheelchair accessibility')
        false: _('Limited wheelchair accessibility')
    -
      key: tactile_paving
      labels:
        true: _('Tactile paving')
        limited: _('Limited tactile paving')
        false: _('No tactile paving')
    -
      key: toilets_wheelchair
      labels:
        true: _('Toilets wheelchair accessible')
        limited: _('Toilets wheelchair accessibility &colon; limited')
        false: _('Toilets not accessible in wheelchair')
- apiName: brewery
  panelName: brewery
- apiName: internet_access
  panelName: internet_access


